name: Github Release

on:
  push:
    tags:  [ "v*.*.*" ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Tags
        run: git fetch --all --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Vue Cli
        run: |
          npm -v
          npm install --location=global @vue/cli

      - name: Build
        run: |
          go version
          go install github.com/rakyll/statik
          export PATH=${PATH}:$(go env GOPATH)/bin
          sed -i "s/\r//g" package.sh     
          make install-vue
          make package-all          

      - name: Release
        env:
          token: ${{ secrets.RELEASE_TOKEN }}
        run: |
          git version
          git remote -v          
          bash release.sh "${token}"