FROM alpine:latest

ENV GOCRON_NODE_VERSION=v2.0.1

RUN apk add --no-cache ca-certificates  tzdata bash \
    &&  mkdir -p /app \
    &&  wget -P /tmp  https://github.com/ppanphper/gocron/releases/download/${GOCRON_NODE_VERSION}/gocron-node-${GOCRON_NODE_VERSION}-linux-amd64.tar.gz \
    &&  cd /tmp \
    &&  tar  zvxf gocron-node-${GOCRON_NODE_VERSION}-linux-amd64.tar.gz  \
    &&  mv /tmp/gocron-node-linux-amd64/gocron-node /app \
    &&  rm  -rf /tmp/* \
    &&  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

WORKDIR /app
EXPOSE 5921

ENTRYPOINT ["/app/gocron-node", "-allow-root"]
